# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/grpc/geodata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/grpc/geodata.proto',
  package='p2.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63ore/grpc/geodata.proto\x12\tp2.common\"\"\n\x0eGeoDataRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"L\n\x0cGeoDataReply\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x11\n\tplaceName\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lng\x18\x04 \x01(\x01\x32J\n\x07GeoData\x12?\n\x07GetData\x12\x19.p2.common.GeoDataRequest\x1a\x17.p2.common.GeoDataReply\"\x00\x62\x06proto3'
)




_GEODATAREQUEST = _descriptor.Descriptor(
  name='GeoDataRequest',
  full_name='p2.common.GeoDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='p2.common.GeoDataRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=72,
)


_GEODATAREPLY = _descriptor.Descriptor(
  name='GeoDataReply',
  full_name='p2.common.GeoDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='p2.common.GeoDataReply.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='placeName', full_name='p2.common.GeoDataReply.placeName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='p2.common.GeoDataReply.lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lng', full_name='p2.common.GeoDataReply.lng', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['GeoDataRequest'] = _GEODATAREQUEST
DESCRIPTOR.message_types_by_name['GeoDataReply'] = _GEODATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoDataRequest = _reflection.GeneratedProtocolMessageType('GeoDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GEODATAREQUEST,
  '__module__' : 'core.grpc.geodata_pb2'
  # @@protoc_insertion_point(class_scope:p2.common.GeoDataRequest)
  })
_sym_db.RegisterMessage(GeoDataRequest)

GeoDataReply = _reflection.GeneratedProtocolMessageType('GeoDataReply', (_message.Message,), {
  'DESCRIPTOR' : _GEODATAREPLY,
  '__module__' : 'core.grpc.geodata_pb2'
  # @@protoc_insertion_point(class_scope:p2.common.GeoDataReply)
  })
_sym_db.RegisterMessage(GeoDataReply)



_GEODATA = _descriptor.ServiceDescriptor(
  name='GeoData',
  full_name='p2.common.GeoData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='p2.common.GeoData.GetData',
    index=0,
    containing_service=None,
    input_type=_GEODATAREQUEST,
    output_type=_GEODATAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GEODATA)

DESCRIPTOR.services_by_name['GeoData'] = _GEODATA

# @@protoc_insertion_point(module_scope)
